FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json ./
RUN npm install
COPY . .
RUN npm run build
RUN npm cache clean --force

FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/build ./build
RUN npm install -g serve
EXPOSE 3000
CMD ["serve", "-s", "build", "-l", "3000"]